webfit_aws_main:
    path: /
    defaults: { _controller: WebfitAWSAppBundle:Default:main }
    methods: [GET]

webfit_aws_ec2:
    path: /{profile}/ec2
    defaults: { _controller: WebfitAWSAppBundle:Default:ec2 }

webfit_aws_ec2_status:
    path: /{profile}/ec2/status
    defaults: { _controller: WebfitAWSAppBundle:Default:ec2Status }

webfit_aws_ec2_provision:
    path: /{profile}/ec2/provision
    defaults: { _controller: WebfitAWSAppBundle:Default:ec2Provision }

webfit_aws_show_schedule:
    path: /{profile}/schedule
    defaults: { _controller: WebfitAWSAppBundle:Default:showSchedule }
    methods: [GET]

webfit_aws_add_schedule_now:
    path: /{profile}/schedule/{asGroup}/{quantity}/now
    defaults: { _controller: WebfitAWSAppBundle:Default:scheduleNow, confirm: null }
    methods: [GET, POST]

webfit_aws_add_schedule_at:
    path: /{profile}/schedule/{asGroup}/{quantity}/{date}/{time}
    defaults: { _controller: WebfitAWSAppBundle:Default:scheduleAt, time: null }
    methods: [GET, POST]

webfit_aws_scaling_historty:
    path: /{profile}/scaling/history/{asGroup}
    defaults: { _controller: WebfitAWSAppBundle:Default:autoScalingHistory, asGroup: null }
    methods: [GET]

webfit_aws_scaling_group_list:
    path: /{profile}/scaling/list
    defaults: { _controller: WebfitAWSAppBundle:Default:autoScalingList }
    methods: [GET]

webfit_aws_scaling_groups:
    path: /{profile}/scaling/groups/{asGroup}
    defaults: { _controller: WebfitAWSAppBundle:Default:autoScalingDetails, asGroup: null }
    methods: [GET]
