# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    webfit.aws.appbundle.aws.class: Webfit\AWS\AppBundle\Service\AWSService

services:
    awsService:
        class: %webfit.aws.appbundle.aws.class%
        arguments: ["@doctrine.orm.default_entity_manager", "@service_container"]
